<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>section_rekomendasi_kain</name>
   <tag></tag>
   <elementGuidId>8d075e89-4ebb-4e50-88bd-dbace24897c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id=&quot;fabric-recommendations&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>&quot;fabric-recommendations&quot;</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
