<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_beli_combed_baby_terry_36_kuning</name>
   <tag></tag>
   <elementGuidId>619673b7-22e7-405e-a262-a07515d120b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>data-testid=&quot;combed-baby-terry-kuning-kenari&quot;</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
